-- Generated by iTin.Export.Writers.Native.SqlScriptWriter
-- Writer: SqlScriptWriter
-- Company: iTin
-- Author: iTin
-- Version: 1

INSERT INTO Inventory VALUES (12001, Nails, 37, 3,99, 147,63)
INSERT INTO Inventory VALUES (12002, Hammer, 5, 12,10, 60,50)
INSERT INTO Inventory VALUES (12003, Saw, 12, 15,37, 184,44)
