//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTin.Export.Queries.SqlServerCe.Sample.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=|DataDirectory|\\Resources\\Database\\ChinookDatabase.sdf")]
        public string ChinookDatabaseConnectionString {
            get {
                return ((string)(this["ChinookDatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\resources\\configuration\\InvoiceConfigurationFile.xml")]
        public string InvoiceExportConfigurationFile {
            get {
                return ((string)(this["InvoiceExportConfigurationFile"]));
            }
            set {
                this["InvoiceExportConfigurationFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\resources\\input\\InvoiceXmlInput.xml")]
        public string InvoiceXmlImput {
            get {
                return ((string)(this["InvoiceXmlImput"]));
            }
            set {
                this["InvoiceXmlImput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\resources\\input\\ProductXmlInput.xml")]
        public string ProductXmlInput {
            get {
                return ((string)(this["ProductXmlInput"]));
            }
            set {
                this["ProductXmlInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\resources\\configuration\\Sample90.xml")]
        public string Sample90 {
            get {
                return ((string)(this["Sample90"]));
            }
            set {
                this["Sample90"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\resources\\configuration\\Sample91.xml")]
        public string Sample91 {
            get {
                return ((string)(this["Sample91"]));
            }
            set {
                this["Sample91"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\resources\\input\\SalesXmlInput.xml")]
        public string SalesXmlInput {
            get {
                return ((string)(this["SalesXmlInput"]));
            }
            set {
                this["SalesXmlInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\resources\\configuration\\Sample92.xml")]
        public string Sample92 {
            get {
                return ((string)(this["Sample92"]));
            }
            set {
                this["Sample92"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\resources\\input\\Sample5XmlInput.xml")]
        public string Sample5XmlInput {
            get {
                return ((string)(this["Sample5XmlInput"]));
            }
            set {
                this["Sample5XmlInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\resources\\configuration\\Sample05.xml")]
        public string Sample05 {
            get {
                return ((string)(this["Sample05"]));
            }
            set {
                this["Sample05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\resources\\configuration\\Sample16.xml")]
        public string Sample16 {
            get {
                return ((string)(this["Sample16"]));
            }
            set {
                this["Sample16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\resources\\input\\SEKRatesXmlInput.xml")]
        public string SEKRatesXmlInput {
            get {
                return ((string)(this["SEKRatesXmlInput"]));
            }
            set {
                this["SEKRatesXmlInput"] = value;
            }
        }
    }
}
